<?php if( ! defined( 'ACCESS' ) ) die( 'DIRECT ACCESS NOT ALLOWED' ); ?>
<body class="is-article-visible" style="background-color:#7dfb64">
				<!-- Intro -->			
							<article class = "mind" style="background-color: #616060;">
							<div class = "close"><a href = "./?page=default">.....</a></div>
								<h2 class="major">About</h2>
								<span class="image main"><img src="assets/images/bg1.jpg" alt="" /></span>
								<p style = "text-align:justify;">Accidents are unexpected and unfortunate things that happen in our daily lives. Every second, minute and hour, this unpredictable events happened. Hence, an emergency response team which includes the ambulance team is necessary at this crucial time where lives of the people are at stake. Despites the advancement of technology, the researchers found out some problems in our society like patients have difficulty in communicating to our ambulance team and ambulances have difficulty in tracking route towards patient’s location that creates slow responsiveness. Also, lack of system in dispatching of the ambulance, manual keeping of the ambulance record, and manual processing in recording and filling of rescue and response record of the patients requires greater effort and time consuming to the employees of the Iloilo City Emergency Responder (ICER).Ambulance Emergency Notification System Using Android Technology helps solve these random problems. Using the mobile application, the client can request immediate help during emergency by simply tapping the emergency alert button that appeared on the mobile application. Emergency requests are received by the system and the longitude and latitude coordinates of the patient’s location are automatically plot on the system. The system provides route towards the patient’s location to guide the ambulance team using Google Map. Notifications which include the emergency request of the client and confirmation to response of the ambulance team on every substation are managed by the admin officer. The system manages the log in account of the admin officer and ambulance team to ensure the security of the system. The admin officer manages the dispatching of the ambulance and the ambulance account which means that the admin officer are allowed to add record, update record, delete record and view the record of each account stored on the system database. Rescue and response report are stored on the system database and it is managed by the admin officer.The promptness of the response team is very essential considering that the life of the patient depends on the hands of the trained personnel and responder. Delays and time constraints to the responses could be minimized. Thus, management complexity could be handled when this system is effectively used. This automated alert management system for emergency response is updated to provide efficiency and hastens the process of alerting the responders and providing them with the easiest way to help the patient.
</p>
							</article>
							</body>
<?php element( 'footer' ); ?>